### ISSUE TITLE
Oh, Thanks. Thats cool

### ISSUE THREAD

**Issue by ghost** [jasperla/openbsd-rockpro64#1]
Could you please add some instructions about building it on OpenBSD/Gentoo
Thanks

If there are also some c00l kids who know android well ? So, if like that please. Please consider leaving your full of information issue. Maybe, on my fork of this repo.

**Comment by jasperla** [comment]
Sorry but I have no interest in OpenBSD/Gentoo at all, you're welcome to fork this repo and figure out the needed steps (of building what exactly?) on said platform.

**Comment by ghost** [comment]
Wow. Is it me writing that issue ? I will fork to add some instructions on how to compile it on linux distros that installed by default on pinebook. Thats what i want to said. 
Thanks for help
